// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8KnFaX4qOsNmhH0jdx-szRpkQIaZoUbw',
    appId: '1:1017771148348:web:6f4bd4ca729392df2eaf39',
    messagingSenderId: '1017771148348',
    projectId: 'sakajobapp',
    authDomain: 'sakajobapp.firebaseapp.com',
    storageBucket: 'sakajobapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ8gaBc1cGwY4s6cpFTtDpWOu415to9Yw',
    appId: '1:1017771148348:android:c5b45ab3258146562eaf39',
    messagingSenderId: '1017771148348',
    projectId: 'sakajobapp',
    storageBucket: 'sakajobapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4kEoMsoFuujlOOWXi5Cd_7eJ-hzEvh0',
    appId: '1:1017771148348:ios:755270d67db331bb2eaf39',
    messagingSenderId: '1017771148348',
    projectId: 'sakajobapp',
    storageBucket: 'sakajobapp.appspot.com',
    iosBundleId: 'com.example.sakajob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4kEoMsoFuujlOOWXi5Cd_7eJ-hzEvh0',
    appId: '1:1017771148348:ios:755270d67db331bb2eaf39',
    messagingSenderId: '1017771148348',
    projectId: 'sakajobapp',
    storageBucket: 'sakajobapp.appspot.com',
    iosBundleId: 'com.example.sakajob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8KnFaX4qOsNmhH0jdx-szRpkQIaZoUbw',
    appId: '1:1017771148348:web:b39c459d4d111a332eaf39',
    messagingSenderId: '1017771148348',
    projectId: 'sakajobapp',
    authDomain: 'sakajobapp.firebaseapp.com',
    storageBucket: 'sakajobapp.appspot.com',
  );
}
